development:
  adapter: postgresql
  encoding: unicode
  database: feeds_development
  pool: 5
  username: david
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: feeds_test
  pool: 5
  username: david
  password:
